# 1. Full path to covsonar data
covsonardata:"path/to/covsonar_data"
prefix:"mutationprofile"
mutation_threshold: 75
# 2. Full path to GInPipe incidence data
GInPipe_cases:"path/to/GInPipe_case_assertainment_data"
total_population:84334787
# 3. Full path to DMS escape fraction data
dms_data:"path/to/DMS_Escape_fraction_data"
# 4. Full path to Clinical VE data for delta variant
VE_delta:""path/to/Clinical_VE_delta"
# 5. Simulation Time frame --- must be included the case timeframe and covsonar timeframe
date_start:"date beginning of simulations"
date_end:"date end of simulations"