# 1a. Full path to GInPipe incidence data
cases: "caseAscertainmentTable_reportedCasesRatio.csv"
# 1b. Fixed total population size for the region of interest
total_population: 84334787
# 2. Focus lineage 
lineage_focus: "BQ.1"
# 3. Weight threshold spikes-group proportions for predictions
weight_prop: 0.01
# 4. Color used in absolute fitness plot
color: "red"
# 5. Plot Fold resistance of DMS sites
FR_DMS_sites: TRUE
# 6. Plot Cross reactivity of all lineages/spikegroups 
Cross_ALL: TRUE
# 7. Add Cross reactivity to specific lineage
added_lineage: "lineage_XXX"
Cross_Lin_file: "results/Cross_react_dic_spikegroups_lineage_XXX.pck"